
security:
  user:
    name: ENC(jE87X9pNJoBL8faDq9oWUg==)
    password: ENC(jE87X9pNJoBL8faDq9oWUg==)
  oauth2:
    client:
      clientId: trustedclient
      clientSecret: trustedclient123
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid

jasypt:
  encryptor:
    password: raon12#$




